# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/cocoapods/specs.git'
target 'YassirTask' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YassirTask
  pod 'Moya'
  pod 'SDWebImage'
  pod 'Resolver', '1.5.0'

  target 'YassirTaskTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YassirTaskUITests' do
    # Pods for testing
  end

end
